export { Header } from './Header/index.tsx';
export { Tabs } from './Tabs/index.tsx';
export { LeftPanel } from './LeftPanel/index.tsx';
export { YaMap } from './Map/index.tsx';
export { Footer } from './Footer/index.tsx';
export { Service } from './Service/index.tsx';
export { Icon } from './Icon/index.tsx';
export { RegistrationSteps } from './RegistrationSteps';
export { Input } from './Input';